---
title: "Tidy Tuesday 08/03/2021"
author: "Michael Mullarkey"
date: "8/9/2021"
output: html_document
---

```{r setup, include=FALSE, cache = FALSE}
require("knitr")
## setting working directory
knitr::opts_chunk$set(echo = TRUE, tidy = TRUE, warning = FALSE, message = FALSE, include = FALSE)

```

```{r}

library(tidytuesdayR)

paralympics <- tidytuesdayR::tt_load("2021-08-03")

athletes <- paralympics$athletes

```

```{r}

library(tidyverse)
library(skimr)

skim(athletes)
glimpse(athletes)

```
```{r identifying top medal getters in history}

top_5_medal <- athletes %>% 
  filter(!is.na(athlete)) %>% 
  group_by(athlete) %>% 
  summarise(n_medals = n()) %>% 
  arrange(desc(n_medals)) %>% 
  slice(1:5) %>% 
  print()

```


```{r getting all data for top medal getters in history}

top_medals <- athletes %>% 
  filter(!is.na(athlete)) %>% 
  group_by(athlete) %>% 
  mutate(n_medals = n()) %>% 
  ungroup() %>% 
  arrange(desc(n_medals)) %>% 
  filter(athlete %in% top_5_medal$athlete) %>% 
  print()

```
```{r tidying athlete name and refactoring medal count}

library(glue)

tidy_medals <- top_medals %>% 
  separate(col = athlete, into = c("last_name", "first_name"), sep = " ") %>% 
  mutate(last_name = tolower(last_name),
         last_name = str_to_title(last_name),
         full_name = glue("{first_name} {last_name}")) %>% 
  group_by(last_name) %>% 
  arrange(year) %>% 
  mutate(medal_n = row_number()) %>% 
  ungroup() %>% 
  print()

```

```{r installing ggtrack if necessary}

# Installation commented out here but you can uncomment if you need to install

library(devtools)
devtools::install_github("mrjoh3/ggtrack")

library(ggtrack)


```


```{r}

library(showtext)

font_add_google(name = "Dancing Script",
                family = "dancing")

showtext::showtext_auto()

p_medal_count <- tidy_medals %>% 
  mutate(medal = as.factor(medal),
         medal = fct_relevel(medal, "Gold", "Silver", "Bronze")) %>% 
  ggplot(aes(full_name, fill = medal)) +
  coord_flip() +
  geom_bar(alpha = 0.6) +
  scale_fill_manual(values = c("darkgoldenrod1", "darkgrey", "darkgoldenrod")) +
  theme_dark() +
  theme(plot.background = element_rect(fill = "grey75"),
        legend.background = element_rect(fill = "grey75"),
        text = element_text(family = "dancing"),
        axis.text.y = element_text(family = "dancing", face = "bold"),
        axis.text.x = element_text(family = "dancing", face = "bold"),
        plot.caption = element_text(hjust = 1.3)) +
  labs(x = " ", y = "Total Number of Medals", fill = "Medal Type",
       title = "Top All-Time Paralympic Medal Winner Has More Golds Than Anyone Else Has Medals",
       subtitle = "All of These Folks Are Swimmers", caption = "Plot by @mcmullarkey, twitter.com/mcmullarkey\nCode: https://github.com/mcmullarkey/tidy_tuesday/")

p_medal_count

ggsave("stacked_bar_08_03_2021.jpg")

```

```{r adding ggtrack to plot}

## Not making this public yet because I can't save the plot in a way I like. Right now for me ggsave only gets the bottom part of the plot with the QR code, not the actual plot I created

p_track <- ggtrack(p_medal_count,
        qr_content = "https://github.com/mcmullarkey/tidy_tuesday/blob/main/tt_08_03_2021.Rmd",
        caption = paste0("Data accessed from #TidyTuesday 08-03-2021 <br> Scan QR code for all cleaning/plotting code <br> Plot by @mcmullarkey"),
        logo = 'https://www.r-project.org/logo/Rlogo.png',
        plot.background = element_rect(fill = "grey75", size = 0))

```

