---
title: "Tidy Tuesday 08/03/2021"
author: "Michael Mullarkey"
date: "8/9/2021"
output: html_document
---

```{r setup, include=FALSE, cache = FALSE}
require("knitr")
## setting working directory
knitr::opts_chunk$set(echo = TRUE, tidy = TRUE, warning = FALSE, message = FALSE, include = FALSE)

```

```{r loading in data}

library(tidytuesdayR)

infrastructure <- tidytuesdayR::tt_load("2021-08-10")

investment <- infrastructure$investment

chain_investment <- infrastructure$chain_investment

ipd <- infrastructure$ipd

```

```{r using a function to skim the different dataframes}

library(tidyverse)
library(skimr)

df_names <- list(investment, chain_investment, ipd)

map(df_names, ~skim(.x))

```

```{r glimpsing the dataframes}

# Had this in a function originally but the output was too messy

glimpse(investment)
glimpse(chain_investment)
glimpse(ipd)

```

```{r}

library(ggridges)
library(showtext)

showtext::showtext_auto()

font_add_google(name = "Roboto Mono",
                family = "roboto")

chain_investment %>% 
  mutate(gross_inv_chain = log(gross_inv_chain + 1)) %>% 
  ggplot(aes(x =  gross_inv_chain, y = meta_cat, fill = meta_cat, color = meta_cat)) +
  geom_density_ridges(alpha = 0.6, jittered_points = TRUE) +
  scale_fill_viridis_d(option = "plasma") +
  scale_color_viridis_d(option = "plasma") +
  theme_dark() +
  theme(legend.position = "none",
        plot.background = element_rect(fill = "black"),
        text = element_text(family = "roboto", color = "white"),
        axis.text = element_text(family = "roboto", color = "white")) +
  labs(y = "", x = "Gross Investment in Logged 2021 Dollars", title = "")
  

```

